Repository epinio/ui, pull requests merged in 2023-09, with the labels that each got.

#333 Select page containing git commit if deploying that specific commit
  dashboard/package.json
  dashboard/yarn.lock
Labels: kind/enhancement

#325 Fix custom variables validation in Application edit mode
  dashboard/pkg/epinio/edit/applications.vue
Labels: kind/bug

#332 Use correct colour for text in home page version blob
  dashboard/pkg/epinio/pages/c/_cluster/dashboard.vue
Labels: 1/10/0

#334 Redirect namespace links in masthead to namespace list with filter
  dashboard/pkg/epinio/list/namespaces.vue
  dashboard/pkg/epinio/models/epinio-namespaced-resource.js
Labels: kind/bug

#336 [fix] Fix binding to an app to a service after that service is created
  dashboard/pkg/epinio/config/epinio.ts
  dashboard/pkg/epinio/edit/bind-apps-mixin.js
Labels: kind/bug

#340 Fix edit service instance
  dashboard/pkg/epinio/edit/bind-apps-mixin.js
  dashboard/pkg/epinio/edit/services.vue
  dashboard/pkg/epinio/l10n/en-us.yaml
Labels: kind/bug

#344 Added `backend` dir to goreleaser config
  backend/.goreleaser.yml
Labels: kind/bug
